---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        name: ${APP_NAME}
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: ${APP_NAME}
        spec:
          containers:
            - name: data-service
              imagePullPolicy: Always
              image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${SERVICE}:${IMAGE_VERSION}
              volumeMounts:
                - name: spring-config
                  mountPath: /deployments/application.properties
                  readOnly: true
                  subPath: application.properties
              env:
                - name: SPRING_CONFIG_LOCATION
                  value: /deployments/application.properties
          volumes:
            - name: spring-config
              configMap:
                name: data-service-configmap
                defaultMode: 440
                items:
                  - key: application.properties
                    path: application.properties

          imagePullSecrets:
            - name: artifactory-puller
      triggers:
        - type: ConfigChange
parameters:
  - name: NAMESPACE
    displayName: Openshift namespace (project)
    description: Openshift namespace (project) this application resides in
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name