---
apiVersion: v1
kind: Template
metadata:
  name: route-template
objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        name: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      host: ${SERVICE}.${NAMESPACE}.${APPS_SUBDOMAIN}
      to:
        kind: Service
        name: ${SERVICE}
      port:
        targetPort: datasvc-port
parameters:
  - name: NAMESPACE
    displayName: Namespace (Openshift project)
    description: Openshift project this application resides in
    required: true
  - name: APPS_SUBDOMAIN
    displayName: Subdomain Route Information (OpenShift cluster)
    description: Subdomain for cluster routes
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name